alloy:
  configMap:
    # -- Create a new ConfigMap for the config file.
    create: true
    # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
    content: |-
      prometheus.exporter.self "default" {
      }

      prometheus.scrape "metamonitoring" {
        targets    = prometheus.exporter.self.default.targets
        forward_to = [prometheus.remote_write.default.receiver]
      }

      prometheus.remote_write "default" {
        endpoint {
          url = "http://mimir-query-frontend.alloy:9009/api/v1/push"
        }
      }

      logging {
        level    = "warn"
        format   = "json"
        write_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint {
          url = "http://loki-gateway.alloy/loki/api/v1/push"
        }
      }
      tracing {
        sampling_fraction = 0.1
        write_to          = [otelcol.exporter.otlp.default.input]
      }

      otelcol.exporter.otlp "default" {
          client {
              endpoint = "tempo-query-frontend.alloy:4317"
          }
      }
    # -- Name of existing ConfigMap to use. Used when create is false.
    # logging {
    #   level = "info"
    #   format = "logfmt"
    #   write_to = [loki.write.default.receiver]
    # }
