apiVersion: v1
kind: Service
metadata:
  name: "{{ namespace }}-db-service"
  namespace: "{{ namespace }}"
spec:
  ports:
    - name: "{{ port-name }}"
      protocol: TCP
      port: { { port } }
      targetPort: "{{ port }}"
      nodePort: 0
  selector: {}

---
apiVersion: v1
kind: Endpoints
metadata:
  name: "{{ namespace }}-db-service"
  namespace: "{{ namespace }}"
subsets:
  - addresses:
      - ip: "{{ server-ip-address }}"
    ports:
      - port: { { port } }
        name: "{{ port-name }}"
