apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
    - name: nginx-app
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      env:
        - name: PROTOCOL
          value: "http"
        - name: PORT
          value: "80"
        - name: HOST
          value: "127.0.0.1"
        - name: SERVICE_ADDRESS
          value: "$(PROTOCOL)://$(HOST):$(PORT)"
