apiVersion: v1
kind: ServiceAccount
metadata:
  name: ADMIN-SA
  namespace: NAMESPACE
secrets:
  - name: ADMIN-SECRET

---
apiVersion: v1
kind: Secret
metadata:
  name: ADMIN-SECRET
  namespace: NAMESPACE
  annotations:
    kubernetes.io/service-account.name: ADMIN-SA
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ADMIN-CR
  namespace: NAMESPACE
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ADMIN-RB
  namespace: NAMESPACE
subjects:
  - kind: ServiceAccount
    name: ADMIN-SA
    namespace: NAMESPACE
roleRef:
  kind: Role
  name: ADMIN-ROLE
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: <cert-authority-data>
      server: https://server.ip.address:6443
    name: CLUSTER
contexts:
  - context:
      cluster: CLUSTER
      user: CLUSTER-ADMIN
    name: CONTEXT
current-context: CONTEXT
kind: Config
users:
  - name: ADMIN
    user:
      token: { secret-token }

---
# kubectl get secrets -n name NAMESPACE
# kubectl describe secrets {token-name} -n name NAMESPACE
