# Convert into tempo chart values from tempo distributed
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

ingester:
  config:
    trace_idle_period: 10s
    max_block_bytes: 1000000
    max_block_duration: 1m

queryFrontend:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
