adminPassword: admin

sidecar:
  enableUniqueFilenames: true
  dashboards:
    enabled: true
    searchNamespace: ALL
    provider:
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    searchNamespace: ALL
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
    serve_from_sub_path: true
ingress:
  enabled: true
  path: /
  hosts: []

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        uid: tempo
        url: http://tempo.monitoring.svc:3100
        isDefault: false
        editable: true
