tempo:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  ingester:
    trace_idle_period: 10s
    max_block_bytes: 1000000
    max_block_duration: 1m

  retention: 1h

persistence:
  enabled: true
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  size: 10Gi
