Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"  
  # config.vm.box = "bento/centos-stream-9"
  
  user = "vbox"
  subnet = "192.168.56.0"
  netmask = "255.255.255.0"

  nodes = [
    { :name => "kube-control-1", :ip => "192.168.56.2" },
    { :name => "worker-1", :ip => "192.168.56.3" },
    { :name => "worker-2", :ip => "192.168.56.4" }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |config|
      config.vm.hostname = node[:name]

      config.vm.network "public_network", bridge: ["en0: Wi-Fi", "en1: Ethernet", "wlan0", "eth0", "wlp0s20f3", "enp3s0"]
      config.vm.network "private_network", ip: node[:ip], subnet: subnet, netmask: netmask

      config.vm.disk :disk, size: "20GB", primary: true

      config.vm.provider "virtualbox" do |vb|
        vb.name = node[:name]
        vb.memory = 2048
        vb.cpus = 2
      end
      config.vm.provision "shell", inline: <<-SHELL
        useradd -m -s /bin/bash -p $(openssl passwd -1 #{user}) #{user}
        usermod -aG sudo #{user}
      SHELL
    end
  end
end
