# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-stream-9"
  config.vm.box_check_update = false

  # Define the nodes
  nodes = [
    { :name => "kube-control-1", :ip => "192.168.56.111" },
    { :name => "kube-worker-1", :ip => "192.168.56.112" },
    { :name => "kube-worker-2", :ip => "192.168.56.113" }
  ]

  # Provision each node
  nodes.each do |node|
    config.vm.define node[:name] do |config|
      config.vm.hostname = node[:name]

      config.vm.network "public_network", bridge: "BRIDGE_INTERFACE_NAME"
      config.vm.network "private_network", ip: node[:ip]

      config.vm.provider "virtualbox" do |vb|
        vb.name = node[:name]
        vb.memory = 2048
        vb.cpus = 2
      end

      config.vm.disk :disk, size: "20GB", primary: true

      config.vm.provision "shell", inline: <<-SHELL
        # Update system
        sudo dnf update -y

        # Install basic packages
        sudo dnf install -y vim net-tools nmap telnet

        # Set timezone
        sudo timedatectl set-timezone Asia/Dhaka

        # Disable SELinux
        sudo setenforce 0
        sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

        # Disable swap
        sudo swapoff -a
        sudo sed -i '/swap/d' /etc/fstab

        # Configure firewall
        sudo systemctl disable --now firewalld
        # sudo systemctl enable --now firewalld
        # sudo firewall-cmd --permanent --add-port={6443,2379-2380,10250,10251,10252,10255}/tcp
        # sudo firewall-cmd --reload

        # Enable IP forwarding
        sudo tee -a /etc/sysctl.conf << EOF
net.ipv4.ip_forward = 1
EOF
        sudo sysctl -p

        # Set up hosts file
        sudo tee -a /etc/hosts << EOF
192.168.56.111 kube-control-1
192.168.56.112 kube-worker-1
192.168.56.113 kube-worker-2
EOF

        # Install container runtime (containerd)
        sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
        sudo dnf install -y containerd.io
        sudo mkdir -p /etc/containerd
        containerd config default | sudo tee /etc/containerd/config.toml
        sudo sed -i 's/\(SystemdCgroup = \).*/\1true/' /etc/containerd/config.toml
        sudo systemctl enable --now containerd

        # Disable apparmor
        sudo systemctl disable --now apparmor
        sudo systemctl restart containerd
        
        # Load necessary modules
        sudo tee /etc/modules-load.d/k8s.conf << EOF
overlay
br_netfilter
EOF
        sudo modprobe overlay
        sudo modprobe br_netfilter

        # Set up required sysctl params
        sudo tee /etc/sysctl.d/k8s.conf << EOF
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF
        sudo sysctl --system
      SHELL
    end
  end
end
